# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostsStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RewritesStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewrite_condition', models.CharField(max_length=800)),
                ('rewrite_location', models.CharField(max_length=800)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.HostsStore')),
            ],
        ),
        migrations.CreateModel(
            name='UserAgentsStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=800)),
            ],
        ),
        migrations.AddField(
            model_name='rewritesstore',
            name='user_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.UserAgentsStore'),
        ),
    ]
